
#global import
from functools import wraps
from matplotlib.patches import Patch
import tensorflow as tf
import functools
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import json
import gc

matplotlib.use('TkAgg') #to see the graph

#local import
from app.domain.sequence_functions import WindowMutationFunctions
from app.domain.genomic_analysis import ImportanceSplicingSearch as iss
from app.domain.genomic_analysis import ImportanceSplicingSearch
from app.domain.spliceai_calculation import one_hot_encoder
from app.domain.initialization.initalize_my_model import my_model
from app.domain.initialization.initialize_internal_gv import my_internal_genetic_variant

#test tools
def print_dic_lisible(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        d = func(*args, **kwargs)

        for muts, genome in d.items():
            print(f"{muts} -> {genome}")

        return d

    return wrapper

def clean_string(s: str) -> str:
    """
    Supprime de la chaîne :
    - les chiffres (0-9)
    - les espaces
    - les retours à la ligne
    """
    return "".join(c for c in s if not c.isdigit() and c not in " \n\t\r")

def plot_mutation_importance(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        # 1. Lecture optimisée du fichier JSON
        with open("app/test/output_gradiant.json", "r") as file:
            payload = json.load(file) # Charge le flux directement
            
        # 2. Reconstitution instantanée de la matrice NumPy
        # On force en float32 pour économiser 50% de RAM sur les gros volumes

        raw_output = np.array(payload["data"], dtype=np.float32)
        
        # 3. Nettoyage des dimensions (identique à ton code d'origine)
        matrix = np.squeeze(raw_output)
        
        if len(matrix.shape) != 2 or matrix.shape[1] != 4:
            raise ValueError(f"La matrice doit avoir une forme finale (N, 4). Forme reçue : {matrix.shape}")
        
        limit = 1e-8
        matrix = np.where(np.abs(matrix) > limit, matrix, 0.0)
        
        seq_len = matrix.shape[0]
        positions = np.arange(seq_len)
        
        # Ordre classique des bases (à adapter selon ton one_hot_encoder)
        bases = ['A', 'C', 'G', 'T']
        colors = {
            'A': '#22c55e', # Vert
            'C': '#2563eb', # Bleu
            'G': '#eab308', # Jaune
            'T': '#dc2626'  # Rouge
        }
        
        # Separer les valeurs positives et négatives
        pos_matrix = np.where(matrix > 0, matrix, 0)
        neg_matrix = np.where(matrix < 0, matrix, 0) # Contient des valeurs négatives
        
        # Initialisation de la figure
        #plt.figure(figsize=(max(10, seq_len * 0.2), 6))
        largeur_securisee = min(30, max(10, seq_len * 0.2))
        plt.figure(figsize=(largeur_securisee, 6))
        
        # --- PARTIE POSITIVE (Empilée vers le haut) ---
        bottom_pos = np.zeros(seq_len)
        for i, base in enumerate(bases):
            values = pos_matrix[:, i]
            plt.bar(positions, values, bottom=bottom_pos, color=colors[base], label=f'{base} (+)')
            bottom_pos += values
            
        # --- PARTIE NÉGATIVE (Empilée vers le bas) ---
        bottom_neg = np.zeros(seq_len)
        for i, base in enumerate(bases):
            values = neg_matrix[:, i] # Valeurs négatives
            plt.bar(positions, values, bottom=bottom_neg, color=colors[base])
            bottom_neg += values # On ajoute un nombre négatif, donc ça descend bien
            
        # Customisation du graphique
        plt.axhline(0, color='black', linewidth=0.8, linestyle='--')
        plt.xlabel("Position dans la séquence (Nucléotides)")
        plt.ylabel("Importance des Mutations (Score de Gradient)")
        plt.title("Cartographie d'Importance des Mutations (Integrated Gradients)")
        
        # Légende unique pour les 4 couleurs
        legend_elements = [Patch(facecolor=colors[b], label=b) for b in bases]
        plt.legend(handles=legend_elements, loc='upper right')
        
        plt.tight_layout()
        plt.show()
        
    return wrapper

def write_in_json(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        output = func(*args, **kwargs)
        if isinstance(output, np.ndarray):
            data_to_save = {"data": output.tolist()}
        else:
            data_to_save = {"data": output}
        with open("app/test/output_gradiant.json", "w") as file:
            json.dump(data_to_save, file)

        return output
    return wrapper

def read_json_file(path):
    with open(path, "r") as file:
        return json.load(file)

def plot_hight_impact_mutation_position(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        output = func(*args, **kwargs)
        
        colors = {
            'up': '#22c55e',       # green
            'down': '#dc2626',     # red
            'bg_intervals': "#62c0ff" # background color to show the intervals
        }

        fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

        intervals = my_internal_genetic_variant.spot_regulation_interval_peaks(output)
        print("Intervalles détectés :", intervals)

        for ax, region in zip(axes, ["donor", "acceptor"]):
            region_intervals = intervals.get(region, [])
            for start, end in region_intervals:
                ax.axvspan(start, end, facecolor=colors['bg_intervals'], alpha=0.3, zorder=0)

            values = np.array(output[region])
            positions = np.arange(len(values))
            bar_colors = [colors['up'] if v > 0 else colors['down'] for v in values]

            ax.bar(positions, values, color=bar_colors, width=1.0, zorder=2)

            ax.axhline(0, color='black', linewidth=0.8, linestyle='--', zorder=3)
            ax.set_ylabel(f"{region.capitalize()} score delta")

            legend_elements = [
                Patch(facecolor=colors['up'], label='Augmente l\'épissage'),
                Patch(facecolor=colors['down'], label='Réduit l\'épissage'),
                Patch(facecolor=colors['bg_intervals'], alpha=0.3, label='Intervalles d\'intérêt')
            ]
            ax.legend(handles=legend_elements, loc='upper right')

        axes[-1].set_xlabel("Position mutée dans la séquence")
        fig.suptitle("Impact des mutations par position sur la probabilité d'épissage")
        plt.tight_layout()
        plt.show()

        return output
    return wrapper
# var test



"""
input_sequence = one_hot_encoder({"genom": sequence})

print("\n---------------------------------------------\n")

print("initial: " + my_internal_genetic_variant.sequence)
my_internal_genetic_variant.insert("ttttctttttttttttttttttt", 0, 0)
print("interm: " + my_internal_genetic_variant.sequence)
my_internal_genetic_variant.mutations=[">p.1.t>a", ">p.5.c>a"]
my_internal_genetic_variant.apply_mutations()
print(f"result: {my_internal_genetic_variant.sequence}")
"""

@plot_hight_impact_mutation_position
def test():
    #sequence = "acatctctgAATGCAGATG"
    sequence1 = """
        ATCCACTTTGCCTTTCTCTCCACAGGTGTCCACTCCCAGTTCAATTACAGCTCTTAAGGCTAGAGTACTTAATACGACTCACTATAGGCTAGCCTCGAGATAATTCCCCCACCACCTCCCATATGTCCAGATTCTCTTGATGATGCTGATGCTTTGGGAAGTATGTTAATTTCATGGTACATGAGTGGCTATCATACTGGCTATTATATGGTAAGTAATCACTCAGCATCTTTTCCTGACAATTTTTTTGTAGTTATGTGACTTTGTTTTGTAAATTTATAAAATACTACTTGCTTCTCTCTTTATATTACTAAAAAATAAAAATAAAAAAATACAACTGTCTGAGGCTTAAATTACTCTTGCATTGTCCCTAAGTATAATTTTAGTTAATTTTAAAAAGCTTTCATGCTATTGTTAGATTATTTTGATTATACACTTTTGAATTGAAATTATACTTTTTCTAAATAATGTTTTAATCTCTGATTTGAAATTGATTGTAGGGAATGGAAAAGATGGGATAATTTTTCATAAATGAAAAATGAAATTCTTTTTTTTTTTTTTTTTTTTTGAGACGGAGTCTTGCTCTGTTGCCCAGGCTGGAGTGCAATGGCGTGATCTTGGCTCACAGCAAGCTCTGCCTCCTGGATTCACGCCATTCTCCTGCCTCAGCCTCAGAGGTAGCTGGGACTACAGTTGCCTGCCACCACGCCTGTCTAATTTTTTGTATTTTTTTGTAAAGACAGGGTTTCACTGTGTTAGCCAGGATGGTCTCAATCTCCTGACCCCGTGATCCACCCGCCTCGGCCTTCCAAGAGAAATGAAATTTTTTTAATGCACAAAGATCTGGGGTAATGTGTACCACATTGAACCTTGGGGAGTATGGCTTCAAACTTGTCACTTTATACGTTAGTCTCCTACGGACATGTTCTATTGTATTTTAGTCAGAACATTTAAAATTATTTTATTTTATTTTATTTTTTTTTTTTTTTTGAGACGGAGTCTCGCTCTGTCACCCAGGCTGGAGTACAGTGGCGCAGTCTCGGCTCACTGCAAGCTCCGCCTCCCGGGTTCACGCCATTCTCCTGCCTCAGCCTCTCCGAGTAGCTGGGACTACAGGCGCCCGCCACCACGCCCGGCTAATTTTTTTTTATTTTTAGTAGAGACGGGGTTTCACCGTGGTCTCGATCTCCTGACCTCGTGATCCACCCGCCTCGGCCTCCCAAAGTGCTGGGATTACAAGCGTGAGCCACCGCGCCCGGCCTAAAATTATTTTTAAAAGTAAGCTCTTGTGCCCTGCTAAAATTATGATGTGATATTGTAGGCACTTGTATTTTTAGTAAATTAATATAGAAGAAACAACTGACTTAAAGGTGTATGTTTTTAAATGTATCATCTGTGTGTGCCCCCATTAATATTCTTATTTAAAAGTTAAGGCCAGACATGGTGGCTTACAACTGTAATCCCAACAGTTTGTGAGGCCGAGGCAGGCAGATCACTTGAGGTCAGGAGTTTGAGACCAGCCTGGCCAACATGATGAAACCTTGTCTCTACTAAAAATACCAAAAAAAATTTAGCCAGGCATGGTGGCACATGCCTGTAATCCGAGCTACTTGGGAGGCTGTGGCAGGAAAATTGCTTTAATCTGGGAGGCAGAGGTTGCAGTGAGTTGAGATTGTGCCACTGCACTCCACCCTTGGTGACAGAGTGAGATTCCGTCTCAAAAAAAGAAAAAGGCCTGGCACGGTGGCTCACACCTATAATCCCAGTACTTTGGGAGGTAGAGGCAGGTGGATCACTTGAGGTTAGGAGTTCAGGACCAGCCTGGCCAACATGGTGACTACTCCATTTCTACTAAATACACAAAACTTAGCCCAGTGGCGGGCAGTTGTAATCCCAGCTACTTGAGAGGTTGAGGCAGGAGAATCACTTGAACCTGGGAGGCAGAGGTTGCAGTGAGCCAAGATCACACCGCTGCACTCTAGCCTGGCCAACAGAGTGAGAATTTGCGGAGGGAAAAAAAAGTCACGCTTCAGTTGTTGTAGTATAACCTTGGTATATTGTATGTATCATGAATTCCTCATTTTAATGACCAAAAAGTAATAAATCAACAGCTTGTAATTTGTTTTGAGATCAGTTATCTGACTGTAACACTGTAGGCTTTTGTGTTTTTTAAATTATGAAATATTTGAAAAAAATACATAATGTATATATAAAGTATTGGTATAATTTATGTTCTAAATAACTTTCTTGAGAAATAATTCACATGGTGTGCAGTTTACCTTTGAAAGTATACAAGTTGGCTGGGCACAATGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCAGGGCAGGTGGATCACGAGGTCAGGAGATCGAGACCATCCTGGCTAACATGGTGAAACCCCGTCTCTACTAAAAGTACAAAAACAAATTAGCCGGGCATGTTGGCGGGCACCTTTTGTCCCAGCTGCTCGGGAGGCTGAGGCAGGAGAGTGGCGTGAACCCAGGAGGTGGAGCTTGCAGTGAGCCGAGATTGTGCCAGTGCACTCCAGCCTGGGCGACAGAGCGAGACTCTGTCTCAAAAAATAAAATAAAAAAGAAAGTATACAAGTCAGTGGTTTTGGTTTTCAGTTATGCAACCATCACTACAATTTAAGAACATTTTCATCACCCCAAAAAGAAACCCTGTTACCTTCATTTTCCCCAGCCCTAGGCAGTCAGTACACTTTCTGTCTCTATGAATTTGTCTATTTTAGATATTATATATAAACGGAATTATACGATATGTGGTCTTTTGTGTCTGGCTTCTTTCACTTAGCATGCTATTTTCAAGATTCATCCATGCTGTAGAATGCACCAGTACTGCATTCCTTCTTATTGCTGAATATTCTGTTGTTTGGTTATATCACATTTTATCCATTCATCAGTTCATGGACATTTAGGTTGTTTTTATTTTTGGGCTATAATGAATAATGTTGCTATGAACATTCGTTTGTGTTCTTTTTGTTTTTTTGGTTTTTTGGGTTTTTTTTGTTTTGTTTTTGTTTTTGAGACAGTCTTGCTCTGTCTCCTAAGCTGGAGTGCAGTGGCATGATCTTGGCTTACTGCAAGCTCTGCCTCCCGGGTTCACACCATTCTCCTGCCTCAGCCCGACAAGTAGCTGGGACTACAGGCGTGTGCCACCATGCACGGCTAATTTTTTGTATTTTTAGTAGAGATGGGGTTTCACCGTGTTAGCCAGGATGGTCTCGATCTCCTGACCTCGTGATCTGCCTGCCTAGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACTGCACCTGGCCTTAAGTGTTTTTAATACGTCATTGCCTTAAGCTAACAATTCTTAACCTTTGTTCTACTGAAGCCACGTGGTTGAGATAGGCTCTGAGTCTAGCTTTTAACCTCTATCTTTTTGTCTTAGAAATCTAAGCAGAATGCAAATGACTAAGAATAATGTTGTTGAAATAACATAAAATAGGTTATAACTTTGATACTCATTAGTAACAAATCTTTCAATACATCTTACGGTCTGTTAGGTGTAGATTAGTAATGAAGTGGGAAGCCACTGCAAGCTAGTATACATGTAGGGAAAGATAGAAAGCATTGAAGCCAGAAGAGAGACAGAGGACATTTGGGCTAGATCTGACAAGAAAAACAAATGTTTTAGTATTAATTTTTGACTTTAAATTTTTTTTTTATTTAGTGAATACTGGTGTTTAATGGTCTCATTTTAATAAGTATGACACAGGTAGTTTAAGGTCATATATTTTATTTGATGAAAATAAGGTATAGGCCGGGCACGGTGGCTCACACCTGTAATCCCAGCACTTTGGGAGGCCGAGGCAGGCGGATCACCTGAGGTCGGGAGTTAGAGACTAGCCTCAACATGGAGAAACCCCGTCTCTACTAAAAAAAATACAAAATTAGGCGGGCGTGGTGGTGCATGCCTGTAATCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATTGCTTGAACCTGGGAGGTGGAGGTTGCGGTGAGCCGAGATCACCTCATTGCACTCCAGCCTGGGCAACAAGAGCAAAACTCCATCTCAAAAAAAAAAAAATAAGGTATAAGCGGGCTCAGGAACATCATTGGACATACTGAAAGAAGAAAAATCAGCTGGGCGCAGTGGCTCACGCCGGTAATCCCAACACTTTGGGAGGCCAAGGCAGGCGAATCACCTGAAGTCGGGAGTTCCAGATCAGCCTGACCAACATGGAGAAACCCTGTCTCTACTAAAAATACAAAACTAGCCGGGCATGGTGGCGCATGCCTGTAATCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATTGCTTGAACCGAGAAGGCGGAGGTTGCGGTGAGCCAAGATTGCACCATTGCACTCCAGCCTGGGCAACAAGAGCGAAACTCCGTCTCAAAAAAAAAAGGAAGAAAAATATTTTTTTAAATTAATTAGTTTATTTATTTTTTAAGATGGAGTTTTGCCCTGTCACCCAGGCTGGGGTGCAATGGTGCAATCTCGGCTCAGTGCAACCTCCGCCTCCTGGGTTCAAGTGATTCTCCTGCCTCAGCTTCCCGAGTAGCTGTGATTACAGCCATATGCCACCACGCCCAGCCAGTTTTGTGTTTTGTTTTGTTTTTTGTTTTTTTTTTTTGAGAGGGTGTCTTGCTCTGTCCCCCAAGCTGGAGTGCAGCGGCGCGATCTTGGCTCACTGCAAGCTCTGCCTCCCAGGTTCACACCATTCTCTTGCCTCAGCCTCCCGAGTAGCTGGGACTACAGGTGCCCGCCACCACACCCGGCTAATTTTTTTGTGTTTTTAGTAGAGATGGGGTTTCACTGTGTTAGCCAGGATGGTCTCGATCTCCTGACCTTTTGATCCACCCGCCTCAGCCTCCCCAAGTGCTGGGATTATAGGCGTGAGCCACTGTGCCCGGCCTAGTCTTGTATTTTTAGTAGAGTCGGGATTTCTCCATGTTGGTCAGGCTGTTCTCCAAATCCGACCTCAGGTGATCCGCCCGCCTTGGCCTCCAAAAGTGCAAGGCAAGGCATTACAGGCATGAGCCACTGTGACCGGCAATGTTTTTAAATTTTTTACATTTAAATTTTATTTTTTAGAGACCAGGTCTCACTCTATTGCTCAGGCTGGAGTGCAAGGGCACATTCACAGCTCACTGCAGCCTTGACCTCCAGGGCTCAAGCAGTCCTCTCACCTCAGTTTCCCGAGTAGCTGGGACTACAGTGATAATGCCACTGCACCTGGCTAATTTTTATTTTTATTTATTTATTTTTTTTTGAGACAGAGTCTTGCTCTGTCACCCAGGCTGGAGTGCAGTGGTGTAAATCTCAGCTCACTGCAGCCTCCGCCTCCTGGGTTCAAGTGATTCTCCTGCCTCAACCTCCCAAGTAGCTGGGATTAGAGGTCCCCACCACCATGCCTGGCTAATTTTTTGTACTTTCAGTAGAAACGGGGTTTTGCCATGTTGGCCAGGCTGTTCTCGAACTCCTGAGCTCAGGTGATCCAACTGTCTCGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACTGTGCCTAGCATGAGCCACCACGCCGGCCTAATTTTTAAATTTTTTGTAGAGACAGGGTCTCATTATGTTGCCCAGGGTGGTGTCAAGCTCCAGGTCTCAAGTGATCCCCCTACCTCCGCCTCCCAAAGTTGTGGGATTGTAGGCATGAGCCACTGCAAGAAAACCTTAACTGCAGCCTAATAATTGTTTTCTTTGGGATAACTTTTAAAGTACATTAAAAGACTATCAACTTAATTTCTGATCATATTTTGTTGAATAAAATAAGTAAAATGTCTTGTGAAACAAAATGCTTTTTAACATCCATATAAAGCTATCTATATATAGCTATCTATGTCTATATAGCTATTTTTTTTAACTTCCTTTATTTTCCTTACAGGGTTTTAGACAAAATCAAAAAGAAGGAAGGTGCTCACATTCCTTAAATTAAGGAGTAAGTCTGCCAGCATTATGAAAGTGAATCTTACTTTTGTAAAACTTTATGGTTTGTGGAAAACAAATGTTTTTGAACATTTAAAAAGTTCAGATGTTAAAAAGTTGAAAGGTTAATGTAAAACAATCAATATTAAAGAATTTTGATGCCAAAACTATTAGATAAAAGGTTAATCTACATCCCTACTAGAATTCTCATACTTAACTGGTTGGTTATGTGGAAGAAACATACTTTCACAATAAAGAGCTTTAGGATATGATGCCATTTTATATCACTAGTAGGCAGACCAGCAGACTTTTTTTTATTGTGATATGGGATAACCTAGGCATA
"""
    sequence2 = """

ACACCAGCAAGTTCAGCCCTCTTCAATCAATATAGGGCCACACACGGACTTTTGACTGACTACTCCCCA
AGTATTTCACATTTTGGGGCCTTATCTCCAGTTTCTCACCACAGTTGTTCATCACTGTGTTTCTTACTAG
CCAGGCGTTTATAAAAACAGTAATACCTAACACTATTGATCACCTACTATAGTGTCAGGCGCTGTAATA

ATATTATTGTGATGATGATGATTATGCTGCTCTTTCTGGCATTGTCATACGTGTATTGCTTGTACTACTCA
CTGAATCTACACAACTGCCCTTATGACATTTACCCTGTTATTATTCCTCTTTTAAGGTAAATACATGAAA
AATGCTTCCCACTTTGCCTTGCTTACTGCTTATTGCTAGTACTGAACAAATGTTAGAACTGAAACTTAG
AGAGGTTATGTGGCTTTACCAAGGTCCCAGAGTTCCTAGGGCAGAGAACAGGATTGTCTACCAGACA
TTTTAATTCTAGTACTATGCATCTTAACCATTACCATAGGCTGACTTACTCTACAGTGTCCAACACTATTC
ATATTAAGATTTATTTAATGACTTTGAAACAGTATTTCATGTCTAAATAGAAAAACTACTAACTCGCATT
TTTAAGAAAATATTGTATCTTGGTTTTTCTTCACTGCTGGCCAGTTTACTAACAATCTGAAATAAAAAGA
AAAAAATATGATAAACTGCTCCCAGTATAAAATACAGAGCTAAGACAAGAACGTTTCATTGGCTTTGAT
TTCCCTAGGGTCCAGCTTCAAATTAATTTACTTCCTATTCAAGGGAATTTTAAATCAGAAAGAAGATCTT
ATCCCATCTTGTTTTGCCTTTGTTTTTTCTTGAATAAAAAAAAAATAAGTAAAATTTATTTCCCTGGCAA
GGTCTGAAAACTTTTGTTTTCTTTACCACTTCCACAATGTATATGATTGTTACTGAGAAGGCTTATTTAA
CTTAAGTTACTTGTCCAGGCATGAGAATGAGCAAAATCGTTTTTTAAAAAATTGTTAAATGTATATTAAT
GAAAAGGTTGAATCTTTTCATTTTCTACCATGTATTGCTAAACAAAGTATCCACATTGTTAGAAAAAGAT
ATATAATGTCATGAATAAGAGTTTGGCTCAAATTGTTACTCTTCAATTAAATTTGACTTATTGTTATTGAA
ATTGGCTCTTTAGCTTGTGTTTCTAATTTTTCTTTTTCTTCTTTTTTCCTTTTTGCAAAAACCCAAAATATT
TTAGCTCCTACTCAGACTGTTACTCTGGTGACACAACCTGTGGTTACTAAGGAAACTGCCATCTCCAA
ACTAGAAATGCCATCTTCCTTGATGTTGGAGGTACCTGCTCTGGCAGATTTCAACCGGGCTTGGACAG
AACTTACCGACTGGCTTTCTCTGCTTGATCAAGTTATAAAATCACAGAGGGTGATGGTGGGTGACCTT
GAGGATATCAACGAGATGATCATCAAGCAGAAGGTATGAGAAAAAATGATAAAAGTTGGCAGAAGTT
TTTCTTTAAAATGAAGATTTTCCACCAATCACTTTACTCTCCTAGACCATTTCCCACCAGTTCTTAGGCA
ACTGTTTCTCTCTCAGCAAACACATTACTCTCACTATTCAGCCTAAGTATAATCAAGGATATAAATTAAT
GCAAATAACAAAAGTAGCCATACATTAAAAAGGAAATATACAAAAAAAAAAAAAAAAAAAAGCAGAA
ACCTTACAAGAATAGTTGTCTCAGTTAAATTTACTAAACAACCTGGTATTTTAAAAATCTATTTTATACC
AAATAAGTCACTCAACTGAGCTATTTACATTTAAACTGTTTGTTTTGGCACTACGCAGCCCAACATATTG
CAGAATCAAATATAATAGTCTGGGAATTGATTATTATCCACTCTTCTAAGTTGTCTGTGCCAATTTGCCT
TCTCCAATGATAAGGATAATTGAAAGAGAGCTATAACTTAAAAAGAGAAAAGTAACAAAACATAAGAT
ATTTAAAATTACCCTAGATCTTAAAGTTGGCATTTATGCAATGCCATGTTCAAATGAACATGTTTTTAAT
ACAAATAGTGCATTTTTCAGCCTCAGTGTAATCCATTTGGTAAAATTATGACATCAACTAGAAACATTAG
AATACATTGATGTAAATATGGTTTACCTAGCTAGATCAAATATACTATATATCTTTTATATTTGTGAATGA
TTAAGAAAAATAATGTTGGAATTGTTATACATTAAAGTTTTTTCACTTGTAACAGCTTTCAAGCCTTTCT
AAAGAAATACAAAGTTGTGCTGAAGGTATTTAGGTATTAAAGTACTACCTTTTGAAAAAACAAGAAGT
GAGGCAGACAGAGTAAGGGGAATTTCTTTGTAAAATAAACTTCACCAATTCCATAGGAATAAAAGTAA
TTTGATAGTAAACAACCTGCATTTAAAGGCCTTGAGCTTGAATACAGAAGACCTGAATTCAGTGCCATT
TGCAAATGATGATTGTGGTCAAGCCATCTCTGGATCTTCGTTTCCTATTCTGAGTACAGAGCATACAGA
GTACACATTCACATTCACAATATAGTTATGGATATGGATGTATATAAATATATGTAAATACTACATATATG
TACCTAAAATTTGTTTTACTTCTGCTTTAAAAAAAGTAATTATAGCCACATTTTT

""".replace("\n", "")
    sequence3 = """TCAGGGTCATCTAATTATTTAGGAAATGCAAGCAGCTTCCCTTAGATGGCACGTTGGTGGTAGCTGTAT
GTGTCTGTGGGGTGTCCAGGCCTGAAACATCAAGACCCATGACTTATCATTTGAATAGATGTGGTACA
CAGTGGCAGATATAGACCCCCTCATGTCCACACAGGCTTTCGTGTGTGCTAACTCCCTCGTGCACTGG
AACGCGGTAATTTCCTGTGCTTCTTTCCAGATCGTGCACAGAACTCTGGCAGCCATGCTGGGTTCCCTT
GCAGCACTGGCAGCACTGGCTGTGATTGGCGATGTAAGTTGTCACAGTCCCAATCCCTGGCTTACCAC
TCAGTGGGATGTCAGCTCAAAGATGTTCCAGGATTCAGGCTTTCGCTGGTTTTTTCACTATTTTATATGC
CACGTCCATGTTTTTGCCCAAGAACCATGCTAGAGGTATGAACTAACAAGCTACAGCATTGAAGAGTA
CTTTTCATTAGGTTTTGTCACACACTCACATCCCAGTGGTGTGATTCCTCATCGTGGTGGAGGAAAGGC
TCCTCATGGGCATGTTTGCCTAGGGCTGTGGAGCTGGGTTGTGATGGGGCTGGATCTGGGTGTTGGA
ACTAGAGGGGACCGTCCTAGCTGGTGCAGAAAGGTGGGAGTCAGTTGGGCCAGGGTCTGTCCTGAA
GAGATCAGGAGGCCCCTGGAGAGGCGTGTTTGGGGATGAGGGTGTCCTGTTTGGCTCG""".replace("\n", "")
    sequence3_short = """AACGCGGTAATTTCCTGTGCTTCTTTCCAGATCGTGCACAGAACTCTGGCAGCCATGCTGGGTTCCCTT
GCAGCACTGGCAGCACTGGCTGTGATTGGCGATGTAAGTTGTCACAGTCCCAATCCCTGGCTTACCAC
TCAGTGGGATGTCAGCTCAAAGATGTTCCAGGATTCAGGCTTTCGCTGGTTTTTTCACTATTTTATATGC
CACGTCCATGTTTTTGCCCAAGAACCATGCTAGAGGTATGAACTAACAAGCTACAGCATTGAAGAGTA
CTTTTCATTAGGTTTTGTCACACACTCACATCCCAGTGGTGTGATTCCTCATCGTGGTGGAGGAAAGGC""".replace("\n", "")
    
    my_internal_genetic_variant.sequence = sequence3 #short right
    gc.collect()
    return my_internal_genetic_variant.hight_impact_mutation_position(base=236, batch_size=32)

def test_run():
    """
    check delta run works
    """
    sequ1 = """TCAGGGTCATCTAATTATTTAGGAAATGCAAGCAGCTTCCCTTAGATGGCACGTTGGTGGTAGCTGTAT
GTGTCTGTGGGGTGTCCAGGCCTGAAACATCAAGACCCATGACTTATCATTTGAATAGATGTGGTACA
CAGTGGCAGATATAGACCCCCTCATGTCCACACAGGCTTTCGTGTGTGCTAACTCCCTCGTGCACTGG
AACGCGGTAATTTCCTGTGCTTCTTTCCAGATCGTGCACAGAACTCTGGCAGCCATGCTGGGTTCCCTT
GCAGCACTGGCAGCACTGGCTGTGATTGGCGATGTAAGTTGTCACAGTCCCAATCCCTGGCTTACCAC
TCAGTGGGATGTCAGCTCAAAGATGTTCCAGGATTCAGGCTTTCGCTGGTTTTTTCACTATTTTATATGC
CACGTCCATGTTTTTGCCCAAGAACCATGCTAGAGGTATGAACTAACAAGCTACAGCATTGAAGAGTA
CTTTTCATTAGGTTTTGTCACACACTCACATCCCAGTGGTGTGATTCCTCATCGTGGTGGAGGAAAGGC
TCCTCATGGGCATGTTTGCCTAGGGCTGTGGAGCTGGGTTGTGATGGGGCTGGATCTGGGTGTTGGA
ACTAGAGGGGACCGTCCTAGCTGGTGCAGAAAGGTGGGAGTCAGTTGGGCCAGGGTCTGTCCTGAA
GAGATCAGGAGGCCCCTGGAGAGGCGTGTTTGGGGATGAGGGTGTCCTGTTTGGCTCG""".replace("\n", "")
    sequ2 = """TCAGGGTCATCTAATTATTTAGGAAATGCAAGCAGCTTCCCTTAGATGGCACGTTGGTGG
TAGCTGTATGTGTCTGTGGGGTGTCCAGGCCTGAAACATCAAGACCCATGACTTATCATT
TGAATAGATGTGGTACACAGTGGCAGATATAGACCCCCTCATGTCCACACAGGCTTTCGT
GTGTGCTAACTCCCTCGTGCACTGGAACGCGGTAATTTCCTGTGCTTCTTTCCAGATCGT
GCACAGAACTCTGGCAGCCATGCTGGGTTCCCTTGCAGCACTGGCAGCACTGGCTGTGAT
TGGCGAAGTAAGTTGTCACAGTCCCAATCCCTGGCTTACCACTCAGTGGGATGTCAGCTC
AAAGATGTTCCAGGATTCAGGCTTTCGCTGGTTTTTTCACTATTTTATATGCCACGTCCA
TGTTTTTGCCCAAGAACCATGCTAGAGGTATGAACTAACAAGCTACAGCATTGAAGAGTA
CTTTTCATTAGGTTTTGTCACACACTCACATCCCAGTGGTGTGATTCCTCATCGTGGTGG
AGGAAAGGCTCCTCATGGGCATGTTTGCCTAGGGCTGTGGAGCTGGGTTGTGATGGGGCT
GGATCTGGGTGTTGGAACTAGAGGGGACCGTCCTAGCTGGTGCAGAAAGGTGGGAGTCAG
TTGGGCCAGGGTCTGTCCTGAAGAGATCAGGAGGCCCCTGGAGAGGCGTGTTTGGGGATG
AGGGTGTCCTGTTTGGCTCG""".replace("\n", "")
    lenght = len(sequ1)
    assert sequ1 != sequ2
    y1 = my_model.run_batches([sequ1 for _ in range(30)])[0]
    y2 = my_model.run_batches([sequ2 for _ in range(30)])[0]
    y1_donor, y1_acceptor = np.array([y1[i][1] for i in range(lenght-1)]), np.array([y1[i][2] for i in range(lenght-1)])
    y2_donor, y2_acceptor = np.array([y2[i][1] for i in range(lenght-1)]), np.array([y2[i][2] for i in range(lenght-1)])
    delta_donor = y2_donor - y1_donor
    delta_acceptor = y2_acceptor - y1_acceptor
    x = [_ for _ in range(len(delta_acceptor))]
    print(f"------x-------{len(x)}\n\n -----------delta_acceptor----------{len(delta_acceptor)}")
    assert len(x) == len(delta_acceptor)
    plt.plot(x, delta_donor, delta_acceptor)
    plt.show()



test_run()
#dico_data = {"donor": np.array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]), "acceptor": np.array([0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0])}
gc.collect()
